theme: jekyll-theme-slate
remote_theme: VNG-Realisatie/jekyll-theme-imvertor
baseurl: "/Waarderingskamer"
nav:
  - title: Demo API
    subnav:
      - title: Main
        path: /
  - title: GitHub Pages 
    subnav:
      - title: Introductie
        path: /intro
      - title: Speciale technieken
        path: /speciale-technieken
github: melk-r/Waarderingskamer
project_name: /Waarderingskamer
